
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - storm.gresearch.co.uk
  resources:
  - topologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storm.gresearch.co.uk
  resources:
  - topologies/finalizers
  verbs:
  - update
- apiGroups:
  - storm.gresearch.co.uk
  resources:
  - topologies/status
  verbs:
  - get
  - patch
  - update
