# permissions for end users to view topologies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topology-viewer-role
rules:
- apiGroups:
  - storm.gresearch.co.uk
  resources:
  - topologies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storm.gresearch.co.uk
  resources:
  - topologies/status
  verbs:
  - get
