# permissions for end users to edit topologies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topology-editor-role
rules:
- apiGroups:
  - storm.gresearch.co.uk
  resources:
  - topologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storm.gresearch.co.uk
  resources:
  - topologies/status
  verbs:
  - get
